name: flutter_template_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  animate_do: ^3.0.2
  flutter_secure_storage: ^8.0.0
  dio: ^5.1.1
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.0.12
  flutter_svg: ^2.0.6
  get_it: ^7.2.0
  hooks_riverpod: ^2.3.3
  intl: ^0.18.1
  stacked_services: ^1.0.0
  firebase_core: ^2.14.0
  equatable: ^2.0.5
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  cloud_functions: ^4.0.7
  google_sign_in: ^5.2.2
  sign_in_with_apple: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
